name: Commit Tagger

on:
  label:
    types: [created, deleted]

jobs:
  tag:
    name: Tagging
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Tag
        run: |
          tag_name=$(date +%s%3N)
          echo "tag_name=$tag_name" >> $GITHUB_ENV
          git tag $tag_name
      - name: Upload
        run: git push origin ${{ env.tag_name }}


