name: Tag Subscriber

on: push

jobs:
  display-tag:
    name: Display push
    runs-on: ubuntu-latest
    steps:
      - name: Show details
        run: |
          repo=${{ github.repository }}
          ref=${{ github.ref }}
          commit=${{ github.sha }}
          echo "$repo/$ref @ $commit"

